### ISSUE TITLE
 DETECTRECENTCONTACTPHOTOS doesn't work anymore

### ISSUE THREAD

**Issue by aurel2222** [smf33/FlickrFollowerBot#4]
Hi,
since last change in FLickr first page, the function 'detectcontactphotos' send zero results.
I think it comes from the get attribute function. I can't see which attribute it has to read...

I would appreciate a little help once again :)

See you soon !

Edit : maybe it is ".activity-card-photos>a.activity-card-photo" we have to change ?

**Comment by aurel2222** [comment]
replace : ".activity-card-photos>a.activity-card-photo by ".photo-link"

done !

**Comment by smf33** [comment]
Hi,
You got it :-)
Flickr update it s website and sometimes use new generated css or html
logic.
All css selector are in config File in order to allow these update easily.

Can t update git code right now but i take the point.
Thanks and good job :-)
Bye



Le sam. 18 juil. 2020 à 18:07, aurel2222 <notifications@github.com> a
écrit :
